name = "FDA"
uuid = "c5e93cf9-584c-45f9-8e8e-8f981c9b431a"
authors = ["Yijun Xie"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
